### ISSUE TITLE
Views Issue

### ISSUE THREAD

**Issue by ars-1** [ars-4/django_media_server#5]
Other than management accounts. Client can also view roles management views like he can add, update or delete packages.

**Comment by ars-4** [comment]
It's resolved. After downloading user has to remove Change web\views.py Categories function from this to:
```
def categories(request):
    if request.user is not None:
        person = Person.objects.get(id=2)

    else:
        person = Person.objects.get(user_id=request.user.id)
    context = {
        'categories': Tag.objects.all(),
        'person': person
    }
    return context
```

<br>

to this:

```
def categories(request):
    context = {
        'categories': Tag.objects.all()
    }
    return context
```

and then create Two accounts initially. First for management. Second for non-management.
and then Change Categories functions back.
